FROM node:23-alpine

WORKDIR /app
COPY ./package*.json ./
RUN npm install

EXPOSE 8080:8080

# docker build -f Dockerfile.dev -t authorization-server/auth-server-web
COPY ./ ./
CMD [ "npm", "run", "start" ]